<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Numera.Host</RootNamespace>
    <AssemblyName>Numera</AssemblyName>
    <OutputType>Exe</OutputType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PredefinedCulturesOnly>false</PredefinedCulturesOnly>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="NodaTime" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Numera.Host.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Numera.Discord\Numera.Discord.csproj" />
    <ProjectReference Include="..\Numera.Application\Numera.Application.csproj" />
    <ProjectReference Include="..\Numera.Persistence.Sqlite\Numera.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\Numera.Analyzers\Numera.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="appsettings.Production.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
