using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Numera.Discord.Generators;

internal sealed class AdapterModule
{
    internal AdapterModule(string typeName, CommandGroupDescriptor? group)
    {
        TypeName = typeName;
        Group = group;
    }

    internal string TypeName { get; }

    internal CommandGroupDescriptor? Group { get; }

    internal List<CommandDescriptor> Commands { get; } = [];

    internal List<AdapterModule> Children { get; } = [];

    internal IEnumerable<string> EndpointTypes =>
        Commands.Select(static command => command.EndpointTypeFullyQualifiedName)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(static name => name, System.StringComparer.Ordinal);
}

internal static class AdapterWriter
{
    private const string Indent = "    ";

    internal static SourceText Write(CommandSurface surface)
    {
        ImmutableArray<AdapterModule> modules = Plan(surface);

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Discord.Interactions;");
        builder.AppendLine("using Numera.Discord.Abstractions;");
        builder.AppendLine("using Numera.Discord.Commands;");
        builder.AppendLine("using Numera.Discord.Gateway;");
        builder.AppendLine();
        builder.AppendLine("namespace Numera.Discord.Routing;");
        builder.AppendLine();

        foreach (AdapterModule module in modules)
        {
            WriteModule(builder, module, depth: 0);
            builder.AppendLine();
        }

        builder.AppendLine("internal static class EconomyGeneratedModules");
        builder.AppendLine("{");
        builder.AppendLine("    internal static readonly Type[] All =");
        builder.AppendLine("    [");

        foreach (AdapterModule module in modules)
        {
            builder.Append("        typeof(").Append(module.TypeName).AppendLine("),");
        }

        builder.AppendLine("    ];");
        builder.AppendLine("}");

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    private static ImmutableArray<AdapterModule> Plan(CommandSurface surface)
    {
        Dictionary<string, AdapterModule> roots = new(System.StringComparer.Ordinal);
        List<AdapterModule> ordered = [];

        foreach (CommandDescriptor command in surface.Commands)
        {
            if (command.GroupPath.IsDefaultOrEmpty)
            {
                AdapterModule flat = Resolve(roots, ordered, command.EndpointTypeDisplayName, null);
                flat.Commands.Add(command);
                continue;
            }

            CommandGroupDescriptor rootGroup = command.GroupPath[0];
            AdapterModule root = Resolve(roots, ordered, rootGroup.Name, rootGroup);

            if (command.GroupPath.Length == 1)
            {
                root.Commands.Add(command);
                continue;
            }

            CommandGroupDescriptor childGroup = command.GroupPath[1];
            AdapterModule child = root.Children
                .FirstOrDefault(candidate => candidate.Group is not null
                    && string.Equals(candidate.Group.Name, childGroup.Name, System.StringComparison.Ordinal));

            if (child is null)
            {
                child = new AdapterModule(ModuleName(rootGroup.Name + "-" + childGroup.Name), childGroup);
                root.Children.Add(child);
            }

            child.Commands.Add(command);
        }

        return [.. ordered];
    }

    private static AdapterModule Resolve(
        Dictionary<string, AdapterModule> roots,
        List<AdapterModule> ordered,
        string key,
        CommandGroupDescriptor? group)
    {
        if (roots.TryGetValue(key, out AdapterModule existing))
        {
            return existing;
        }

        AdapterModule created = new(ModuleName(key), group);
        roots[key] = created;
        ordered.Add(created);

        return created;
    }

    private static string ModuleName(string key)
    {
        StringBuilder builder = new();
        bool upper = true;

        foreach (char character in key)
        {
            if (character is '-' or '_' or ' ' or '.' or '+' or ':')
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        if (builder.Length == 0 || !char.IsLetter(builder[0]))
        {
            builder.Insert(0, 'E');
        }

        return builder.Append("Module").ToString();
    }

    private static void WriteModule(StringBuilder builder, AdapterModule module, int depth)
    {
        string pad = Repeat(depth);

        if (module.Group is not null)
        {
            builder.Append(pad).Append("[Group(\"").Append(Escape(module.Group.Name))
                .Append("\", \"").Append(Escape(module.Group.Description)).AppendLine("\")]");
        }

        builder.Append(pad).Append("public sealed class ").Append(module.TypeName)
            .AppendLine(" : InteractionModuleBase<SocketInteractionContext>");
        builder.Append(pad).AppendLine("{");

        string[] endpoints = [.. module.EndpointTypes];

        foreach (string endpoint in endpoints)
        {
            builder.Append(pad).Append(Indent).Append("private readonly ").Append(endpoint)
                .Append(' ').Append(FieldName(endpoint)).AppendLine(";");
        }

        builder.Append(pad).Append(Indent)
            .AppendLine("private readonly IGeneratedEndpointDispatcher dispatcher;");
        builder.AppendLine();

        builder.Append(pad).Append(Indent).Append("public ").Append(module.TypeName).AppendLine("(");

        foreach (string endpoint in endpoints)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(endpoint)
                .Append(' ').Append(FieldName(endpoint)).AppendLine(",");
        }

        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("IGeneratedEndpointDispatcher dispatcher)");
        builder.Append(pad).Append(Indent).AppendLine("{");

        foreach (string endpoint in endpoints)
        {
            string field = FieldName(endpoint);
            builder.Append(pad).Append(Indent).Append(Indent).Append("ArgumentNullException.ThrowIfNull(")
                .Append(field).AppendLine(");");
        }

        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("ArgumentNullException.ThrowIfNull(dispatcher);");
        builder.AppendLine();

        foreach (string endpoint in endpoints)
        {
            string field = FieldName(endpoint);
            builder.Append(pad).Append(Indent).Append(Indent).Append("this.").Append(field)
                .Append(" = ").Append(field).AppendLine(";");
        }

        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("this.dispatcher = dispatcher;");
        builder.Append(pad).Append(Indent).AppendLine("}");

        foreach (CommandDescriptor command in module.Commands
            .OrderBy(static command => command.Kind)
            .ThenBy(static command => command.Name, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteCommand(builder, command, depth + 1);
        }

        foreach (AdapterModule child in module.Children
            .OrderBy(static child => child.TypeName, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteModule(builder, child, depth + 1);
        }

        builder.Append(pad).AppendLine("}");
    }

    private static void WriteCommand(StringBuilder builder, CommandDescriptor command, int depth)
    {
        string pad = Repeat(depth);
        string field = FieldName(command.EndpointTypeFullyQualifiedName);

        switch (command.Kind)
        {
            case CommandKind.User:
                builder.Append(pad).Append("[UserCommand(\"").Append(Escape(command.Name)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(command.Name.Length == 0 ? "Invoke" : MethodName(command))
                    .AppendLine("(global::Discord.IUser user)");
                break;
            case CommandKind.Message:
                builder.Append(pad).Append("[MessageCommand(\"").Append(Escape(command.Name)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(MethodName(command))
                    .AppendLine("(global::Discord.IMessage message)");
                break;
            default:
                builder.Append(pad).Append("[SlashCommand(\"").Append(Escape(command.Name))
                    .Append("\", \"").Append(Escape(command.Description ?? string.Empty)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(MethodName(command)).Append('(');
                WriteParameters(builder, command);
                builder.AppendLine(")");
                break;
        }

        builder.Append(pad).AppendLine("{");
        builder.Append(pad).Append(Indent).AppendLine("DiscordEndpointResponse response =");
        builder.Append(pad).Append(Indent).Append(Indent).Append("await ").Append(field).Append('.')
            .Append(command.EndpointMethodName).AppendLine("(");
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .Append("dispatcher.CreateContext(Context, \"").Append(Escape(command.CanonicalPath)).AppendLine("\"),");

        WriteArguments(builder, command, pad);

        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent).AppendLine("await dispatcher.DispatchAsync(");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("Context,");
        builder.Append(pad).Append(Indent).Append(Indent).Append("DiscordInteractionKind.")
            .Append(Kind(command.Kind)).AppendLine(",");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("response,");
        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.Append(pad).AppendLine("}");
    }

    private static void WriteParameters(StringBuilder builder, CommandDescriptor command)
    {
        OptionDescriptor[] ordered = Ordered(command);

        for (int index = 0; index < ordered.Length; index++)
        {
            OptionDescriptor option = ordered[index];

            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append("[Summary(\"").Append(Escape(option.Name)).Append("\", \"")
                .Append(Escape(option.Description)).Append("\")] ")
                .Append(option.TypeFullyQualifiedName).Append(' ').Append(ParameterName(option.Name));

            if (!option.Required)
            {
                builder.Append(" = default!");
            }
        }
    }

    private static void WriteArguments(StringBuilder builder, CommandDescriptor command, string pad)
    {
        if (command.Kind == CommandKind.User)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .AppendLine("dispatcher.CreateUserInput(user),");
            return;
        }

        if (command.Kind == CommandKind.Message)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .AppendLine("dispatcher.CreateMessageInput(message),");
            return;
        }

        foreach (OptionDescriptor option in command.Options)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .Append(ParameterName(option.Name)).AppendLine(",");
        }
    }

    private static OptionDescriptor[] Ordered(CommandDescriptor command) =>
    [
        .. command.Options.Where(static option => option.Required),
        .. command.Options.Where(static option => !option.Required),
    ];

    private static string Kind(CommandKind kind) => kind switch
    {
        CommandKind.User => "UserCommand",
        CommandKind.Message => "MessageCommand",
        _ => "SlashCommand",
    };

    private static string MethodName(CommandDescriptor command)
    {
        int separator = command.EndpointMethodName.LastIndexOf('.');
        string name = separator < 0
            ? command.EndpointMethodName
            : command.EndpointMethodName.Substring(separator + 1);

        return name + "Adapter";
    }

    private static string FieldName(string endpointTypeDisplayName)
    {
        int separator = endpointTypeDisplayName.LastIndexOf('.');
        string name = separator < 0
            ? endpointTypeDisplayName
            : endpointTypeDisplayName.Substring(separator + 1);

        StringBuilder builder = new();

        foreach (char character in name)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(character);
            }
        }

        if (builder.Length == 0)
        {
            return "endpoint";
        }

        builder[0] = char.ToLowerInvariant(builder[0]);

        return builder.ToString();
    }

    private static string ParameterName(string optionName)
    {
        StringBuilder builder = new();
        bool upper = false;

        foreach (char character in optionName)
        {
            if (character is '-' or '_' or ' ')
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        if (builder.Length == 0)
        {
            return "value";
        }

        builder[0] = char.ToLowerInvariant(builder[0]);

        return "@" + builder.ToString();
    }

    private static string Repeat(int depth)
    {
        StringBuilder builder = new();

        for (int index = 0; index < depth; index++)
        {
            builder.Append(Indent);
        }

        return builder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
