using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Numera.Discord.Generators;

internal sealed class AdapterAutocomplete
{
    internal AdapterAutocomplete(
        string commandName,
        string commandPath,
        string optionName,
        string providerType,
        string providerMethod)
    {
        CommandName = commandName;
        CommandPath = commandPath;
        OptionName = optionName;
        ProviderType = providerType;
        ProviderMethod = providerMethod;
    }

    internal string CommandName { get; }

    internal string CommandPath { get; }

    internal string OptionName { get; }

    internal string ProviderType { get; }

    internal string ProviderMethod { get; }
}

internal sealed class AdapterInteraction
{
    internal AdapterInteraction(HandlerDescriptor handler, ModalFormDescriptor? form, string transportName)
    {
        Handler = handler;
        Form = form;
        TransportName = transportName;
    }

    internal HandlerDescriptor Handler { get; }

    internal ModalFormDescriptor? Form { get; }

    internal string TransportName { get; }

    internal bool IsModal => Form is not null;
}

internal sealed class AdapterModule
{
    internal AdapterModule(string typeName, CommandGroupDescriptor? group)
    {
        TypeName = typeName;
        Group = group;
    }

    internal string TypeName { get; }

    internal CommandGroupDescriptor? Group { get; }

    internal List<CommandDescriptor> Commands { get; } = [];

    internal List<AdapterModule> Children { get; } = [];

    internal List<AdapterAutocomplete> Autocompletes { get; } = [];

    internal List<AdapterInteraction> Interactions { get; } = [];

    internal IEnumerable<string> EndpointTypes =>
        Commands.Select(static command => command.EndpointTypeFullyQualifiedName)
            .Concat(Autocompletes.Select(static entry => entry.ProviderType))
            .Concat(Interactions.Select(static entry => entry.Handler.EndpointTypeFullyQualifiedName))
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(static name => name, System.StringComparer.Ordinal);
}

internal static class AdapterWriter
{
    private const string Indent = "    ";
    private const string CustomIdPrefix = "bank:v1:";
    private const string ButtonKind = "btn";
    private const string SelectKind = "sel";
    private const string ModalKind = "modal";

    internal static SourceText Write(CommandSurface surface)
    {
        ImmutableArray<AdapterModule> modules = Plan(surface);
        ImmutableArray<AdapterModule> interactions = PlanInteractions(surface);

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Discord.Interactions;");
        builder.AppendLine("using Numera.Discord.Abstractions;");
        builder.AppendLine("using Numera.Discord.Commands;");
        builder.AppendLine("using Numera.Discord.Gateway;");
        builder.AppendLine();
        builder.AppendLine("namespace Numera.Discord.Routing;");
        builder.AppendLine();

        foreach (AdapterModule module in modules)
        {
            WriteModule(builder, module, depth: 0);
            builder.AppendLine();
        }

        WriteTransportForms(builder, interactions);

        foreach (AdapterModule module in interactions)
        {
            WriteModule(builder, module, depth: 0);
            builder.AppendLine();
        }

        builder.AppendLine("internal static class EconomyGeneratedModules");
        builder.AppendLine("{");
        builder.AppendLine("    internal static readonly Type[] All =");
        builder.AppendLine("    [");

        foreach (AdapterModule module in modules.Concat(interactions))
        {
            builder.Append("        typeof(").Append(module.TypeName).AppendLine("),");
        }

        builder.AppendLine("    ];");
        builder.AppendLine("}");
        builder.AppendLine();

        WriteModalFormCatalog(builder, interactions);

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    private static ImmutableArray<AdapterModule> PlanInteractions(CommandSurface surface)
    {
        Dictionary<string, AdapterModule> roots = new(System.StringComparer.Ordinal);
        List<AdapterModule> ordered = [];

        foreach (HandlerDescriptor handler in surface.Components)
        {
            Attach(roots, ordered, handler, null);
        }

        foreach (HandlerDescriptor handler in surface.Modals)
        {
            ModalFormDescriptor? form = surface.ModalForms.FirstOrDefault(candidate => string.Equals(
                candidate.TypeFullyQualifiedName,
                handler.DeclaredInputTypeFullyQualifiedName,
                System.StringComparison.Ordinal));

            if (form is null)
            {
                continue;
            }

            Attach(roots, ordered, handler, form);
        }

        return [.. ordered];
    }

    private static void Attach(
        Dictionary<string, AdapterModule> roots,
        List<AdapterModule> ordered,
        HandlerDescriptor handler,
        ModalFormDescriptor? form)
    {
        AdapterModule module = Resolve(
            roots, ordered, Qualified(handler.EndpointTypeFullyQualifiedName) + "-interactions", null);

        module.Interactions.Add(new AdapterInteraction(
            handler, form, form is null ? string.Empty : TransportName(form)));
    }

    private static ImmutableArray<AdapterModule> Plan(CommandSurface surface)
    {
        Dictionary<string, AdapterModule> roots = new(System.StringComparer.Ordinal);
        List<AdapterModule> ordered = [];

        foreach (CommandDescriptor command in surface.Commands)
        {
            if (command.GroupPath.IsDefaultOrEmpty)
            {
                AdapterModule flat = Resolve(roots, ordered, command.EndpointTypeDisplayName, null);
                flat.Commands.Add(command);
                continue;
            }

            CommandGroupDescriptor rootGroup = command.GroupPath[0];
            AdapterModule root = Resolve(roots, ordered, rootGroup.Name, rootGroup);

            if (command.GroupPath.Length == 1)
            {
                root.Commands.Add(command);
                continue;
            }

            CommandGroupDescriptor childGroup = command.GroupPath[1];
            AdapterModule child = root.Children
                .FirstOrDefault(candidate => candidate.Group is not null
                    && string.Equals(candidate.Group.Name, childGroup.Name, System.StringComparison.Ordinal));

            if (child is null)
            {
                child = new AdapterModule(ModuleName(rootGroup.Name + "-" + childGroup.Name), childGroup);
                root.Children.Add(child);
            }

            child.Commands.Add(command);
        }

        foreach (AdapterModule module in ordered)
        {
            AttachAutocompletes(module, surface);

            foreach (AdapterModule child in module.Children)
            {
                AttachAutocompletes(child, surface);
            }
        }

        return [.. ordered];
    }

    private static void AttachAutocompletes(AdapterModule module, CommandSurface surface)
    {
        foreach (CommandDescriptor command in module.Commands)
        {
            foreach (OptionDescriptor option in command.Options)
            {
                if (string.IsNullOrEmpty(option.AutocompleteProviderKey))
                {
                    continue;
                }

                HandlerDescriptor? provider = surface.AutocompleteProviders.FirstOrDefault(
                    candidate => string.Equals(
                        candidate.Key, option.AutocompleteProviderKey, System.StringComparison.Ordinal));

                if (provider is null)
                {
                    continue;
                }

                module.Autocompletes.Add(new AdapterAutocomplete(
                    command.Name,
                    command.CanonicalPath,
                    option.Name,
                    provider.EndpointTypeFullyQualifiedName,
                    provider.EndpointMethodName));
            }
        }
    }

    private static AdapterModule Resolve(
        Dictionary<string, AdapterModule> roots,
        List<AdapterModule> ordered,
        string key,
        CommandGroupDescriptor? group)
    {
        if (roots.TryGetValue(key, out AdapterModule existing))
        {
            return existing;
        }

        AdapterModule created = new(ModuleName(key), group);
        roots[key] = created;
        ordered.Add(created);

        return created;
    }

    private static string ModuleName(string key)
    {
        StringBuilder builder = new();
        bool upper = true;

        foreach (char character in key)
        {
            if (character is '-' or '_' or ' ' or '.' or '+' or ':')
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        if (builder.Length == 0 || !char.IsLetter(builder[0]))
        {
            builder.Insert(0, 'E');
        }

        return builder.Append("Module").ToString();
    }

    private static void WriteModule(StringBuilder builder, AdapterModule module, int depth)
    {
        string pad = Repeat(depth);

        if (module.Group is not null)
        {
            builder.Append(pad).Append("[Group(\"").Append(Escape(module.Group.Name))
                .Append("\", \"").Append(Escape(module.Group.Description)).AppendLine("\")]");
        }

        builder.Append(pad).Append("public sealed class ").Append(module.TypeName)
            .AppendLine(" : InteractionModuleBase<SocketInteractionContext>");
        builder.Append(pad).AppendLine("{");

        string[] endpoints = [.. module.EndpointTypes];

        foreach (string endpoint in endpoints)
        {
            builder.Append(pad).Append(Indent).Append("private readonly ").Append(endpoint)
                .Append(' ').Append(FieldName(endpoint)).AppendLine(";");
        }

        builder.Append(pad).Append(Indent)
            .AppendLine("private readonly IGeneratedEndpointDispatcher dispatcher;");
        builder.AppendLine();

        builder.Append(pad).Append(Indent).Append("public ").Append(module.TypeName).AppendLine("(");

        foreach (string endpoint in endpoints)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(endpoint)
                .Append(' ').Append(FieldName(endpoint)).AppendLine(",");
        }

        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("IGeneratedEndpointDispatcher dispatcher)");
        builder.Append(pad).Append(Indent).AppendLine("{");

        foreach (string endpoint in endpoints)
        {
            string field = FieldName(endpoint);
            builder.Append(pad).Append(Indent).Append(Indent).Append("ArgumentNullException.ThrowIfNull(")
                .Append(field).AppendLine(");");
        }

        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("ArgumentNullException.ThrowIfNull(dispatcher);");
        builder.AppendLine();

        foreach (string endpoint in endpoints)
        {
            string field = FieldName(endpoint);
            builder.Append(pad).Append(Indent).Append(Indent).Append("this.").Append(field)
                .Append(" = ").Append(field).AppendLine(";");
        }

        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("this.dispatcher = dispatcher;");
        builder.Append(pad).Append(Indent).AppendLine("}");

        foreach (CommandDescriptor command in module.Commands
            .OrderBy(static command => command.Kind)
            .ThenBy(static command => command.Name, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteCommand(builder, command, depth + 1);
        }

        foreach (AdapterAutocomplete entry in module.Autocompletes
            .OrderBy(static entry => entry.CommandName, System.StringComparer.Ordinal)
            .ThenBy(static entry => entry.OptionName, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteAutocomplete(builder, entry, depth + 1);
        }

        foreach (AdapterInteraction entry in module.Interactions
            .OrderBy(static entry => entry.IsModal)
            .ThenBy(static entry => entry.Handler.Key, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteInteraction(builder, entry, depth + 1);
        }

        foreach (AdapterModule child in module.Children
            .OrderBy(static child => child.TypeName, System.StringComparer.Ordinal))
        {
            builder.AppendLine();
            WriteModule(builder, child, depth + 1);
        }

        builder.Append(pad).AppendLine("}");
    }


    private static void WriteAutocomplete(StringBuilder builder, AdapterAutocomplete entry, int depth)
    {
        string pad = Repeat(depth);
        string field = FieldName(entry.ProviderType);

        builder.Append(pad).Append("[AutocompleteCommand(\"").Append(Escape(entry.OptionName))
            .Append("\", \"").Append(Escape(entry.CommandName)).AppendLine("\")]");
        builder.Append(pad).Append("public async Task ").Append(MethodName(entry)).AppendLine("()");
        builder.Append(pad).AppendLine("{");
        builder.Append(pad).Append(Indent)
            .AppendLine("System.Collections.Generic.IReadOnlyList<DiscordAutocompleteOption> options =");
        builder.Append(pad).Append(Indent).Append(Indent).Append("await ").Append(field).Append('.')
            .Append(entry.ProviderMethod).AppendLine("(");
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .Append("dispatcher.CreateAutocompleteRequest(Context, \"").Append(Escape(entry.CommandPath))
            .AppendLine("\"),");
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent)
            .AppendLine("await dispatcher.DispatchAutocompleteAsync(");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("Context,");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("options,");
        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.Append(pad).AppendLine("}");
    }

    private static string MethodName(AdapterAutocomplete entry) =>
        ModuleName(entry.CommandName + "-" + entry.OptionName).Replace("Module", string.Empty) + "Autocomplete";

    private static void WriteInteraction(StringBuilder builder, AdapterInteraction entry, int depth)
    {
        string pad = Repeat(depth);
        string field = FieldName(entry.Handler.EndpointTypeFullyQualifiedName);
        string kind = entry.IsModal
            ? ModalKind
            : entry.Handler.ComponentKind == ComponentKind.Select ? SelectKind : ButtonKind;
        string route = CustomIdPrefix + kind + ":" + entry.Handler.Key;

        builder.Append(pad).Append(entry.IsModal ? "[ModalInteraction(\"" : "[ComponentInteraction(\"")
            .Append(Escape(route)).AppendLine(":*\", true)]");
        builder.Append(pad).Append("public async Task ").Append(InteractionMethodName(entry))
            .Append("(string sessionToken");

        if (entry.IsModal)
        {
            builder.Append(", ").Append(entry.TransportName).AppendLine(" transport)");
        }
        else if (entry.Handler.ComponentKind == ComponentKind.Select)
        {
            builder.AppendLine(", string[] values)");
        }
        else
        {
            builder.AppendLine(")");
        }

        builder.Append(pad).AppendLine("{");
        builder.Append(pad).Append(Indent).AppendLine("DiscordEndpointContext context =");
        builder.Append(pad).Append(Indent).Append(Indent)
            .Append("await dispatcher.CreateContextAsync(Context, \"").Append(Escape(route))
            .AppendLine("\", sessionToken, CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent).AppendLine("DiscordEndpointResponse response =");
        builder.Append(pad).Append(Indent).Append(Indent).Append("await ").Append(field).Append('.')
            .Append(entry.Handler.EndpointMethodName).AppendLine("(");
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).AppendLine("context,");

        if (entry.IsModal)
        {
            WriteFormMapping(builder, entry, pad);
        }
        else
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .Append("new DiscordComponentInput(\"").Append(Escape(entry.Handler.Key))
                .Append("\", sessionToken")
                .AppendLine(entry.Handler.ComponentKind == ComponentKind.Select ? ", values)," : "),");
        }

        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent).AppendLine("await dispatcher.DispatchAsync(");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("Context,");
        builder.Append(pad).Append(Indent).Append(Indent).Append("DiscordInteractionKind.")
            .Append(InteractionKind(entry)).AppendLine(",");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("response,");
        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.Append(pad).AppendLine("}");
    }

    private static void WriteFormMapping(StringBuilder builder, AdapterInteraction entry, string pad)
    {
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).Append("new ")
            .Append(entry.Form!.TypeFullyQualifiedName).AppendLine();
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).AppendLine("{");

        foreach (ModalFieldDescriptor field in entry.Form.Fields)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).Append(Indent)
                .Append(field.PropertyName).Append(" = transport.").Append(field.PropertyName).AppendLine(",");
        }

        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).AppendLine("},");
    }

    private static string InteractionKind(AdapterInteraction entry) => entry.IsModal
        ? "ModalSubmit"
        : entry.Handler.ComponentKind == ComponentKind.Select ? "SelectMenu" : "Button";

    private static string InteractionMethodName(AdapterInteraction entry)
    {
        string suffix = entry.IsModal
            ? "Modal"
            : entry.Handler.ComponentKind == ComponentKind.Select ? "Select" : "Button";

        return ModuleName(entry.Handler.Key).Replace("Module", string.Empty) + suffix + "Adapter";
    }

    private static void WriteTransportForms(StringBuilder builder, ImmutableArray<AdapterModule> interactions)
    {
        foreach (ModalFormDescriptor form in Forms(interactions))
        {
            builder.Append("public sealed class ").Append(TransportName(form)).AppendLine(" : IModal");
            builder.AppendLine("{");
            builder.Append(Indent).Append("public string Title => \"").Append(Escape(form.Title))
                .AppendLine("\";");

            foreach (ModalFieldDescriptor field in form.Fields)
            {
                builder.AppendLine();
                builder.Append(Indent).Append("[InputLabel(\"").Append(Escape(field.Label)).AppendLine("\")]");
                builder.Append(Indent).Append("[ModalTextInput(\"").Append(Escape(field.CustomId))
                    .Append("\", global::Discord.TextInputStyle.").Append(Style(field))
                    .Append(", \"").Append(Escape(field.Placeholder)).Append("\", ")
                    .Append(field.MinimumLength).Append(", ").Append(field.MaximumLength).AppendLine(")]");
                builder.Append(Indent).Append("[RequiredInput(")
                    .Append(field.Required ? "true" : "false").AppendLine(")]");
                builder.Append(Indent).Append("public string ").Append(field.PropertyName)
                    .AppendLine(" { get; set; } = string.Empty;");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }
    }

    private static void WriteModalFormCatalog(StringBuilder builder, ImmutableArray<AdapterModule> interactions)
    {
        AdapterInteraction[] modals =
        [
            .. interactions.SelectMany(static module => module.Interactions)
                .Where(static entry => entry.IsModal)
                .OrderBy(static entry => entry.Handler.Key, System.StringComparer.Ordinal),
        ];

        builder.AppendLine("internal sealed class EconomyGeneratedModalFormCatalog : IModalFormCatalog");
        builder.AppendLine("{");

        foreach (AdapterInteraction entry in modals)
        {
            builder.Append(Indent).Append("private static readonly DiscordModalFieldDefinition[] ")
                .Append(FieldsName(entry)).AppendLine(" =");
            builder.Append(Indent).AppendLine("[");

            foreach (ModalFieldDescriptor field in entry.Form!.Fields)
            {
                builder.Append(Indent).Append(Indent).Append("new DiscordModalFieldDefinition(\"")
                    .Append(Escape(field.CustomId)).Append("\", \"").Append(Escape(field.Label))
                    .Append("\", \"").Append(Escape(field.Placeholder))
                    .Append("\", EconomyModalFieldStyle.").Append(Style(field)).Append(", ")
                    .Append(field.Required ? "true" : "false").Append(", ")
                    .Append(field.MinimumLength).Append(", ").Append(field.MaximumLength).AppendLine("),");
            }

            builder.Append(Indent).AppendLine("];");
            builder.AppendLine();
        }

        builder.Append(Indent)
            .AppendLine("public System.Collections.Generic.IReadOnlyList<DiscordModalFieldDefinition> Resolve(");
        builder.Append(Indent).Append(Indent).AppendLine("string action) => action switch");
        builder.Append(Indent).AppendLine("{");

        foreach (AdapterInteraction entry in modals)
        {
            builder.Append(Indent).Append(Indent).Append('"').Append(Escape(entry.Handler.Key))
                .Append("\" => ").Append(FieldsName(entry)).AppendLine(",");
        }

        builder.Append(Indent).Append(Indent)
            .AppendLine("_ => System.Array.Empty<DiscordModalFieldDefinition>(),");
        builder.Append(Indent).AppendLine("};");
        builder.AppendLine("}");
    }

    private static IEnumerable<ModalFormDescriptor> Forms(ImmutableArray<AdapterModule> interactions) =>
        interactions.SelectMany(static module => module.Interactions)
            .Where(static entry => entry.IsModal)
            .Select(static entry => entry.Form!)
            .GroupBy(static form => form.TypeFullyQualifiedName, System.StringComparer.Ordinal)
            .Select(static group => group.First())
            .OrderBy(static form => form.TypeFullyQualifiedName, System.StringComparer.Ordinal);

    private static string Style(ModalFieldDescriptor field) =>
        field.Style == ModalFieldStyle.Paragraph ? "Paragraph" : "Short";

    private static string FieldsName(AdapterInteraction entry) =>
        ModuleName(entry.Handler.Key).Replace("Module", string.Empty) + "Fields";

    private static string TransportName(ModalFormDescriptor form) =>
        ShortName(form.TypeFullyQualifiedName) + "Transport";

    private static string ShortName(string displayName)
    {
        int separator = displayName.LastIndexOf('.');

        return separator < 0 ? displayName : displayName.Substring(separator + 1);
    }

    private static string Qualified(string fullyQualifiedName) =>
        fullyQualifiedName.StartsWith("global::", System.StringComparison.Ordinal)
            ? fullyQualifiedName.Substring("global::".Length)
            : fullyQualifiedName;
    private static void WriteCommand(StringBuilder builder, CommandDescriptor command, int depth)
    {
        string pad = Repeat(depth);
        string field = FieldName(command.EndpointTypeFullyQualifiedName);

        switch (command.Kind)
        {
            case CommandKind.User:
                builder.Append(pad).Append("[UserCommand(\"").Append(Escape(command.Name)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(command.Name.Length == 0 ? "Invoke" : MethodName(command))
                    .AppendLine("(global::Discord.IUser user)");
                break;
            case CommandKind.Message:
                builder.Append(pad).Append("[MessageCommand(\"").Append(Escape(command.Name)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(MethodName(command))
                    .AppendLine("(global::Discord.IMessage message)");
                break;
            default:
                builder.Append(pad).Append("[SlashCommand(\"").Append(Escape(command.Name))
                    .Append("\", \"").Append(Escape(command.Description ?? string.Empty)).AppendLine("\")]");
                builder.Append(pad).Append("public async Task ").Append(MethodName(command)).Append('(');
                WriteParameters(builder, command);
                builder.AppendLine(")");
                break;
        }

        builder.Append(pad).AppendLine("{");
        builder.Append(pad).Append(Indent).AppendLine("DiscordEndpointContext context =");
        builder.Append(pad).Append(Indent).Append(Indent)
            .Append("await dispatcher.CreateContextAsync(Context, \"").Append(Escape(command.CanonicalPath))
            .AppendLine("\", string.Empty, CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent).AppendLine("DiscordEndpointResponse response =");
        builder.Append(pad).Append(Indent).Append(Indent).Append("await ").Append(field).Append('.')
            .Append(command.EndpointMethodName).AppendLine("(");
        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent).AppendLine("context,");

        WriteArguments(builder, command, pad);

        builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.AppendLine();
        builder.Append(pad).Append(Indent).AppendLine("await dispatcher.DispatchAsync(");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("Context,");
        builder.Append(pad).Append(Indent).Append(Indent).Append("DiscordInteractionKind.")
            .Append(Kind(command.Kind)).AppendLine(",");
        builder.Append(pad).Append(Indent).Append(Indent).AppendLine("response,");
        builder.Append(pad).Append(Indent).Append(Indent)
            .AppendLine("CancellationToken.None).ConfigureAwait(false);");
        builder.Append(pad).AppendLine("}");
    }

    private static void WriteParameters(StringBuilder builder, CommandDescriptor command)
    {
        OptionDescriptor[] ordered = Ordered(command);

        for (int index = 0; index < ordered.Length; index++)
        {
            OptionDescriptor option = ordered[index];

            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append("[Summary(\"").Append(Escape(option.Name)).Append("\", \"")
                .Append(Escape(option.Description)).Append("\")] ")
                .Append(option.TypeFullyQualifiedName).Append(' ').Append(ParameterName(option.Name));

            if (!option.Required)
            {
                builder.Append(" = default!");
            }
        }
    }

    private static void WriteArguments(StringBuilder builder, CommandDescriptor command, string pad)
    {
        if (command.Kind == CommandKind.User)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .AppendLine("dispatcher.CreateUserInput(user),");
            return;
        }

        if (command.Kind == CommandKind.Message)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .AppendLine("dispatcher.CreateMessageInput(message),");
            return;
        }

        foreach (OptionDescriptor option in command.Options)
        {
            builder.Append(pad).Append(Indent).Append(Indent).Append(Indent)
                .Append(ParameterName(option.Name)).AppendLine(",");
        }
    }

    private static OptionDescriptor[] Ordered(CommandDescriptor command) =>
    [
        .. command.Options.Where(static option => option.Required),
        .. command.Options.Where(static option => !option.Required),
    ];

    private static string Kind(CommandKind kind) => kind switch
    {
        CommandKind.User => "UserCommand",
        CommandKind.Message => "MessageCommand",
        _ => "SlashCommand",
    };

    private static string MethodName(CommandDescriptor command)
    {
        int separator = command.EndpointMethodName.LastIndexOf('.');
        string name = separator < 0
            ? command.EndpointMethodName
            : command.EndpointMethodName.Substring(separator + 1);

        return name + "Adapter";
    }

    private static string FieldName(string endpointTypeDisplayName)
    {
        int separator = endpointTypeDisplayName.LastIndexOf('.');
        string name = separator < 0
            ? endpointTypeDisplayName
            : endpointTypeDisplayName.Substring(separator + 1);

        StringBuilder builder = new();

        foreach (char character in name)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(character);
            }
        }

        if (builder.Length == 0)
        {
            return "endpoint";
        }

        builder[0] = char.ToLowerInvariant(builder[0]);

        return builder.ToString();
    }

    private static string ParameterName(string optionName)
    {
        StringBuilder builder = new();
        bool upper = false;

        foreach (char character in optionName)
        {
            if (character is '-' or '_' or ' ')
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        if (builder.Length == 0)
        {
            return "value";
        }

        builder[0] = char.ToLowerInvariant(builder[0]);

        return "@" + builder.ToString();
    }

    private static string Repeat(int depth)
    {
        StringBuilder builder = new();

        for (int index = 0; index < depth; index++)
        {
            builder.Append(Indent);
        }

        return builder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
