<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Numera.Discord</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net.WebSocket" />
    <PackageReference Include="Discord.Net.Interactions" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Numera.Discord.Tests" />
    <InternalsVisibleTo Include="Numera.Host.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Numera.Discord.Abstractions\Numera.Discord.Abstractions.csproj" />
    <ProjectReference Include="..\Numera.Application\Numera.Application.csproj" />
    <ProjectReference Include="..\Numera.Discord.Generators\Numera.Discord.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Numera.Analyzers\Numera.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
